/**
 * CityPulse Jaipur – City Configuration
 * 9 Administrative Zones, Pink Line Metro Stations, Bus Corridors, Weights & Civic Thresholds.
 */

import {
  Zone,
  MetroStation,
  BusCorridor,
  PulseWeights,
  PulseThresholds,
} from '../types';

export const JAIPUR_COORDINATES = {
  lat: 26.9124,
  lng: 75.7873,
  zoom: 12,
};

export const JAIPUR_ZONES: Zone[] = [
  {
    id: 'walled-city',
    nameEn: 'Walled City (Char Diwari)',
    nameHi: 'चारदीवारी (परकोटा)',
    code: 'JP-WC',
    center: { lat: 26.9248, lng: 75.8246 },
    bounds: [
      { lat: 26.915, lng: 75.812 },
      { lat: 26.935, lng: 75.838 },
    ],
    adjacentZoneIds: ['amer', 'raja-park', 'cscheme-civillines'],
    populationWeight: 0.18,
    areaSqKm: 9.8,
    descriptionEn: 'Historic UNESCO World Heritage core, dense heritage bazaars, tourist concentration and vibrant traditional trade.',
    descriptionHi: 'यूनेस्को विश्व धरोहर क्षेत्र, घनी आबादी वाले ऐतिहासिक बाज़ार, भारी पर्यटक आवागमन और पारंपरिक व्यापार।',
    keyLandmarks: ['Hawa Mahal', 'City Palace', 'Jantar Mantar', 'Badi Chaupar', 'Johari Bazar', 'Tripolia'],
    wardNumbers: [55, 56, 57, 58, 59, 60, 61, 62],
  },
  {
    id: 'mansarovar',
    nameEn: 'Mansarovar',
    nameHi: 'मानसरोवर',
    code: 'JP-MS',
    center: { lat: 26.8656, lng: 75.7627 },
    bounds: [
      { lat: 26.845, lng: 75.742 },
      { lat: 26.885, lng: 75.782 },
    ],
    adjacentZoneIds: ['sanganer', 'cscheme-civillines', 'vaishali-nagar'],
    populationWeight: 0.16,
    areaSqKm: 14.5,
    descriptionEn: 'Major residential and institutional hub, host to City Park, metro origin terminal and large student population.',
    descriptionHi: 'प्रमुख आवासीय और शैक्षणिक केंद्र, सिटी पार्क, मेट्रो आरंभिक टर्मिनल और विशाल छात्र आबादी।',
    keyLandmarks: ['City Park Mansarovar', 'VT Road Bazaars', 'Mansarovar Metro Depot', 'Shipra Path', 'Technology Park'],
    wardNumbers: [25, 26, 27, 28, 29, 30],
  },
  {
    id: 'malviya-nagar',
    nameEn: 'Malviya Nagar',
    nameHi: 'मालवीय नगर',
    code: 'JP-MN',
    center: { lat: 26.8530, lng: 75.8172 },
    bounds: [
      { lat: 26.838, lng: 75.802 },
      { lat: 26.872, lng: 75.832 },
    ],
    adjacentZoneIds: ['jagatpura', 'sanganer', 'raja-park'],
    populationWeight: 0.14,
    areaSqKm: 11.2,
    descriptionEn: 'Commercial retail center with high vehicular density along JLN Marg, MNIT educational corridor and Calgiri medical cluster.',
    descriptionHi: 'व्यावसायिक खुदरा केंद्र, जेएलएन मार्ग पर सघन यातायात, एमएनआईटी परिसर और कैलगरी चिकित्सा क्षेत्र।',
    keyLandmarks: ['World Trade Park (WTP)', 'Gaurav Tower (GT)', 'MNIT Campus', 'Apex Hospital', 'Calgiri Marg'],
    wardNumbers: [38, 39, 40, 41, 42],
  },
  {
    id: 'vaishali-nagar',
    nameEn: 'Vaishali Nagar',
    nameHi: 'वैशाली नगर',
    code: 'JP-VN',
    center: { lat: 26.9069, lng: 75.7410 },
    bounds: [
      { lat: 26.888, lng: 75.722 },
      { lat: 26.925, lng: 75.760 },
    ],
    adjacentZoneIds: ['mansarovar', 'cscheme-civillines'],
    populationWeight: 0.12,
    areaSqKm: 12.8,
    descriptionEn: 'Rapidly growing western suburban affluent commercial-residential zone with intense retail clusters along Amrapali and Gandhi Path.',
    descriptionHi: 'तीव्र गति से बढ़ता पश्चिमी समृद्ध आवासीय-व्यावसायिक क्षेत्र, आम्रपाली और गांधी पथ पर व्यापक खुदरा बाज़ार।',
    keyLandmarks: ['Amrapali Circle', 'Gandhi Path', 'National Handloom', 'Vaishali Circle', 'Queens Road Junction'],
    wardNumbers: [15, 16, 17, 18, 19, 20],
  },
  {
    id: 'raja-park',
    nameEn: 'Raja Park',
    nameHi: 'राजा पार्क',
    code: 'JP-RP',
    center: { lat: 26.8970, lng: 75.8280 },
    bounds: [
      { lat: 26.885, lng: 75.815 },
      { lat: 26.912, lng: 75.845 },
    ],
    adjacentZoneIds: ['walled-city', 'malviya-nagar', 'cscheme-civillines'],
    populationWeight: 0.08,
    areaSqKm: 6.4,
    descriptionEn: 'Dense vibrant culinary and shopping district nestled against the Moti Doongri hillocks and Birla Mandir foothills.',
    descriptionHi: 'मोती डूंगरी और बिरला मंदिर के समीप सघन खानपान और खुदरा व्यापार का जीवंत केंद्र।',
    keyLandmarks: ['Raja Park Main Market', 'LBS College Marg', 'Birla Mandir View', 'Dungari Ganesh Foothills', 'Tilak Nagar Border'],
    wardNumbers: [65, 66, 67, 68],
  },
  {
    id: 'sanganer',
    nameEn: 'Sanganer',
    nameHi: 'सांगानेर',
    code: 'JP-SG',
    center: { lat: 26.8150, lng: 75.7725 },
    bounds: [
      { lat: 26.790, lng: 75.750 },
      { lat: 26.838, lng: 75.795 },
    ],
    adjacentZoneIds: ['mansarovar', 'malviya-nagar'],
    populationWeight: 0.11,
    areaSqKm: 18.0,
    descriptionEn: 'Handicraft, textile block printing and industrial belt hosting Jaipur International Airport with mixed industrial and cargo logistics.',
    descriptionHi: 'सांगानेरी ब्लॉक प्रिंटिंग व हस्तशिल्प औद्योगिक क्षेत्र, जयपुर अंतरराष्ट्रीय हवाई अड्डा और मालवाहक लॉजिस्टिक्स।',
    keyLandmarks: ['Jaipur International Airport (JAI)', 'Sanganer Block Print Cluster', 'Shri Digambar Jain Atishaya Kshetra', 'Kagzi Paper Mills'],
    wardNumbers: [31, 32, 33, 34, 35],
  },
  {
    id: 'amer',
    nameEn: 'Amer',
    nameHi: 'आमेर',
    code: 'JP-AM',
    center: { lat: 26.9855, lng: 75.8513 },
    bounds: [
      { lat: 26.950, lng: 75.825 },
      { lat: 27.015, lng: 75.885 },
    ],
    adjacentZoneIds: ['walled-city'],
    populationWeight: 0.06,
    areaSqKm: 22.4,
    descriptionEn: 'Historic northern fort fortress corridor, eco-sensitive Aravalli ridges, elephant village and major international tourist draw.',
    descriptionHi: 'उत्तरी ऐतिहासिक दुर्ग गलियारा, अरावली पर्यावरण-संवेदनशील क्षेत्र, हाथी गांव और प्रमुख अंतरराष्ट्रीय पर्यटन स्थल।',
    keyLandmarks: ['Amer Fort & Palace', 'Jaigarh Fort', 'Maota Lake', 'Nahargarh Biological Park', 'Elephant Village (Hathi Gaon)'],
    wardNumbers: [1, 2, 3, 4],
  },
  {
    id: 'jagatpura',
    nameEn: 'Jagatpura',
    nameHi: 'जगतपुरा',
    code: 'JP-JG',
    center: { lat: 26.8220, lng: 75.8450 },
    bounds: [
      { lat: 26.798, lng: 75.820 },
      { lat: 26.848, lng: 75.875 },
    ],
    adjacentZoneIds: ['malviya-nagar'],
    populationWeight: 0.07,
    areaSqKm: 16.2,
    descriptionEn: 'Expanding southeastern institutional and health metropolis hosting large specialized hospitals, engineering academies and rail junction.',
    descriptionHi: 'दक्षिण-पूर्वी विस्तार क्षेत्र, सुपर-स्पेशियलिटी अस्पताल, इंजीनियरिंग कॉलेज और जगतपुरा रेलवे जंक्शन।',
    keyLandmarks: ['Bombay Hospital', 'Jagatpura Railway Station', 'Mahal Road High-Rise Corridor', 'SKIT University Zone'],
    wardNumbers: [43, 44, 45, 46],
  },
  {
    id: 'cscheme-civillines',
    nameEn: 'C-Scheme & Civil Lines',
    nameHi: 'सी-स्कीम व सिविल लाइन्स',
    code: 'JP-CS',
    center: { lat: 26.9050, lng: 75.7980 },
    bounds: [
      { lat: 26.890, lng: 75.778 },
      { lat: 26.920, lng: 75.815 },
    ],
    adjacentZoneIds: ['walled-city', 'mansarovar', 'vaishali-nagar', 'raja-park'],
    populationWeight: 0.08,
    areaSqKm: 8.5,
    descriptionEn: 'State administrative heart, Secretariat, Governor House, Central Park joggers, high-end diplomatic cafes and financial avenues.',
    descriptionHi: 'राज्य का प्रशासनिक हृदय, शासन सचिवालय, राजभवन, सेंट्रल पार्क, राजनयिक कैफ़े और वित्तीय केंद्र।',
    keyLandmarks: ['Statue Circle', 'Government Secretariat', 'Raj Bhavan', 'Central Park & Musical Fountain', 'Ashok Nagar M.I. Road Link'],
    wardNumbers: [48, 49, 50, 51, 52],
  },
];

export const JAIPUR_METRO_STATIONS: MetroStation[] = [
  {
    id: 'st-01',
    nameEn: 'Mansarovar',
    nameHi: 'मानसरोवर',
    stationNumber: 1,
    coordinates: { lat: 26.8660, lng: 75.7610 },
    zoneId: 'mansarovar',
    isInterchange: false,
    line: 'pink',
  },
  {
    id: 'st-02',
    nameEn: 'New Aatish Market',
    nameHi: 'न्यू आतिश मार्केट',
    stationNumber: 2,
    coordinates: { lat: 26.8778, lng: 75.7662 },
    zoneId: 'mansarovar',
    isInterchange: false,
    line: 'pink',
  },
  {
    id: 'st-03',
    nameEn: 'Vivek Vihar',
    nameHi: 'विवेक विहार',
    stationNumber: 3,
    coordinates: { lat: 26.8872, lng: 75.7708 },
    zoneId: 'mansarovar',
    isInterchange: false,
    line: 'pink',
  },
  {
    id: 'st-04',
    nameEn: 'Shyam Nagar',
    nameHi: 'श्याम नगर',
    stationNumber: 4,
    coordinates: { lat: 26.8942, lng: 75.7745 },
    zoneId: 'cscheme-civillines',
    isInterchange: false,
    line: 'pink',
  },
  {
    id: 'st-05',
    nameEn: 'Ram Nagar',
    nameHi: 'राम नगर',
    stationNumber: 5,
    coordinates: { lat: 26.9015, lng: 75.7791 },
    zoneId: 'cscheme-civillines',
    isInterchange: false,
    line: 'pink',
  },
  {
    id: 'st-06',
    nameEn: 'Civil Lines',
    nameHi: 'सिविल लाइन्स',
    stationNumber: 6,
    coordinates: { lat: 26.9080, lng: 75.7870 },
    zoneId: 'cscheme-civillines',
    isInterchange: false,
    line: 'pink',
  },
  {
    id: 'st-07',
    nameEn: 'Railway Station (Jaipur Jn)',
    nameHi: 'रेलवे स्टेशन (जयपुर जंक्शन)',
    stationNumber: 7,
    coordinates: { lat: 26.9198, lng: 75.7925 },
    zoneId: 'cscheme-civillines',
    isInterchange: true,
    line: 'pink',
  },
  {
    id: 'st-08',
    nameEn: 'Sindhi Camp (Bus Hub)',
    nameHi: 'सिंधी कैंप (बस स्टैंड)',
    stationNumber: 8,
    coordinates: { lat: 26.9228, lng: 75.8015 },
    zoneId: 'cscheme-civillines',
    isInterchange: true,
    line: 'pink',
  },
  {
    id: 'st-09',
    nameEn: 'Chandpole',
    nameHi: 'चांदपोल',
    stationNumber: 9,
    coordinates: { lat: 26.9255, lng: 75.8115 },
    zoneId: 'walled-city',
    isInterchange: false,
    line: 'pink',
  },
  {
    id: 'st-10',
    nameEn: 'Chhoti Chaupar',
    nameHi: 'छोटी चौपड़',
    stationNumber: 10,
    coordinates: { lat: 26.9249, lng: 75.8202 },
    zoneId: 'walled-city',
    isInterchange: false,
    line: 'pink',
  },
  {
    id: 'st-11',
    nameEn: 'Badi Chaupar (Hawa Mahal)',
    nameHi: 'बड़ी चौपड़ (हवा महल)',
    stationNumber: 11,
    coordinates: { lat: 26.9238, lng: 75.8290 },
    zoneId: 'walled-city',
    isInterchange: false,
    line: 'pink',
  },
];

export const JAIPUR_BUS_CORRIDORS: BusCorridor[] = [
  {
    id: 'corridor-tonk-rd',
    nameEn: 'Tonk Road Rapid Corridor',
    nameHi: 'टोंक रोड त्वरित गलियारा',
    routeCode: 'JCTSL-1A',
    zoneIds: ['sanganer', 'malviya-nagar', 'cscheme-civillines'],
    startPoint: 'Sanganer Thana / Airport Gate',
    endPoint: 'Ajmeri Gate (Char Diwari)',
    frequencyMinutes: 6,
    dailyRidershipApprox: 62000,
  },
  {
    id: 'corridor-jln-marg',
    nameEn: 'JLN Marg Arterial Route',
    nameHi: 'जेएलएन मार्ग मुख्य मार्ग',
    routeCode: 'JCTSL-2B',
    zoneIds: ['jagatpura', 'malviya-nagar', 'raja-park', 'cscheme-civillines'],
    startPoint: 'Jagatpura University Cluster',
    endPoint: 'Statue Circle & New Gate',
    frequencyMinutes: 8,
    dailyRidershipApprox: 54000,
  },
  {
    id: 'corridor-ajmer-rd',
    nameEn: 'Ajmer Road Express Link',
    nameHi: 'अजमेर रोड एक्सप्रेस लिंक',
    routeCode: 'JCTSL-3C',
    zoneIds: ['mansarovar', 'vaishali-nagar', 'cscheme-civillines'],
    startPoint: '200 Feet Bypass DCM',
    endPoint: 'Jaipur Railway Junction',
    frequencyMinutes: 10,
    dailyRidershipApprox: 48000,
  },
  {
    id: 'corridor-sikar-rd',
    nameEn: 'Sikar Road – Amber Gateway',
    nameHi: 'सीकर रोड – आमेर प्रवेश मार्ग',
    routeCode: 'JCTSL-4D',
    zoneIds: ['amer', 'walled-city'],
    startPoint: 'Amer Fort Kunda Bus Stop',
    endPoint: 'Chhoti Chaupar / Chandpole',
    frequencyMinutes: 12,
    dailyRidershipApprox: 38000,
  },
  {
    id: 'corridor-mi-rd',
    nameEn: 'MI Road & Central Circulator',
    nameHi: 'एम.आई. रोड व केंद्रीय परिक्रमा',
    routeCode: 'JCTSL-5E',
    zoneIds: ['walled-city', 'cscheme-civillines'],
    startPoint: 'Khasa Kothi Circle',
    endPoint: 'Sanganeri Gate',
    frequencyMinutes: 5,
    dailyRidershipApprox: 71000,
  },
];

/**
 * 8 Key Jaipur Traffic Corridors monitored via Google Maps Routes API (computeRoutes)
 */
export interface TrafficCorridor {
  id: string;
  nameEn: string;
  nameHi: string;
  originName: string;
  destinationName: string;
  origin: { lat: number; lng: number };
  destination: { lat: number; lng: number };
  mappedZoneIds: string[];
  baseDistanceKm: number;
  typicalDurationMinutes: number;
}

export const JAIPUR_TRAFFIC_CORRIDORS: TrafficCorridor[] = [
  {
    id: 'tonk-road',
    nameEn: 'Tonk Road (Narayan Singh Circle → Sanganer)',
    nameHi: 'टोंक रोड (नारायण सिंह सर्किल → सांगानेर)',
    originName: 'Narayan Singh Circle',
    destinationName: 'Sanganer Police Thana / Airport Gate',
    origin: { lat: 26.8998, lng: 75.8152 },
    destination: { lat: 26.8225, lng: 75.7725 },
    mappedZoneIds: ['cscheme-civillines', 'malviya-nagar', 'sanganer'],
    baseDistanceKm: 11.2,
    typicalDurationMinutes: 24,
  },
  {
    id: 'jln-marg',
    nameEn: 'JLN Marg (Rajasthan University → Jawahar Circle)',
    nameHi: 'जेएलएन मार्ग (राजस्थान विश्वविद्यालय → जवाहर सर्किल)',
    originName: 'Rajasthan University Main Gate',
    destinationName: 'Jawahar Circle Garden',
    origin: { lat: 26.8905, lng: 75.8180 },
    destination: { lat: 26.8402, lng: 75.8035 },
    mappedZoneIds: ['raja-park', 'malviya-nagar', 'jagatpura'],
    baseDistanceKm: 7.8,
    typicalDurationMinutes: 16,
  },
  {
    id: 'ajmer-road',
    nameEn: 'Ajmer Road (Sodala → Heerapura)',
    nameHi: 'अजमेर रोड (सोडाला → हीरापुरा)',
    originName: 'Sodala Elevated Flyover',
    destinationName: 'Heerapura 200 Feet Bypass',
    origin: { lat: 26.9015, lng: 75.7745 },
    destination: { lat: 26.8860, lng: 75.7285 },
    mappedZoneIds: ['cscheme-civillines', 'vaishali-nagar', 'mansarovar'],
    baseDistanceKm: 6.5,
    typicalDurationMinutes: 14,
  },
  {
    id: 'sikar-road',
    nameEn: 'Sikar Road (Chomu Puliya → Road No. 14)',
    nameHi: 'सीकर रोड (चोमू पुलिया → रोड नं. 14 वीकेआईए)',
    originName: 'Chomu Puliya Circle',
    destinationName: 'VKIA Road No. 14 Industrial Cut',
    origin: { lat: 26.9535, lng: 75.7795 },
    destination: { lat: 27.0125, lng: 75.7660 },
    mappedZoneIds: ['walled-city', 'amer'],
    baseDistanceKm: 8.4,
    typicalDurationMinutes: 18,
  },
  {
    id: 'delhi-road',
    nameEn: 'Delhi Road (Zorawar Singh Gate → Amer)',
    nameHi: 'दिल्ली रोड (जोरावर सिंह गेट → आमेर)',
    originName: 'Zorawar Singh Gate',
    destinationName: 'Amer Fort Kunda',
    origin: { lat: 26.9385, lng: 75.8340 },
    destination: { lat: 26.9855, lng: 75.8513 },
    mappedZoneIds: ['walled-city', 'amer'],
    baseDistanceKm: 7.2,
    typicalDurationMinutes: 17,
  },
  {
    id: 'mi-road',
    nameEn: 'MI Road (Ajmeri Gate → Panch Batti)',
    nameHi: 'एमआई रोड (अजमेरी गेट → पांच बत्ती)',
    originName: 'Ajmeri Gate',
    destinationName: 'Panch Batti / Khasa Kothi',
    origin: { lat: 26.9168, lng: 75.8205 },
    destination: { lat: 26.9185, lng: 75.8010 },
    mappedZoneIds: ['walled-city', 'cscheme-civillines'],
    baseDistanceKm: 2.3,
    typicalDurationMinutes: 8,
  },
  {
    id: 'gopalpura-bypass',
    nameEn: 'Gopalpura Bypass (Tonk Road → Gurjar ki Thadi)',
    nameHi: 'गोपालपुरा बाईपास (टोंक रोड → गुर्जर की थड़ी)',
    originName: 'Tonk Road Gopalpura Junction',
    destinationName: 'Gurjar ki Thadi Underpass',
    origin: { lat: 26.8655, lng: 75.8010 },
    destination: { lat: 26.8795, lng: 75.7665 },
    mappedZoneIds: ['malviya-nagar', 'mansarovar'],
    baseDistanceKm: 5.1,
    typicalDurationMinutes: 13,
  },
  {
    id: 'new-sanganer-road',
    nameEn: 'New Sanganer Road (Sodala → Mansarovar)',
    nameHi: 'न्यू सांगानेर रोड (सोडाला → मानसरोवर)',
    originName: 'Sodala Metro Junction',
    destinationName: 'Mansarovar VT Road Crossing',
    origin: { lat: 26.8965, lng: 75.7720 },
    destination: { lat: 26.8580, lng: 75.7605 },
    mappedZoneIds: ['cscheme-civillines', 'mansarovar'],
    baseDistanceKm: 5.6,
    typicalDurationMinutes: 15,
  },
];

export const PULSE_WEIGHTS: PulseWeights = {
  traffic: 0.25,
  water: 0.20,
  airQuality: 0.15,
  sanitation: 0.15,
  transit: 0.10,
  crowd: 0.10,
  power: 0.05,
};

export const PULSE_THRESHOLDS: PulseThresholds = {
  optimalMin: 78,
  moderateMin: 55,
  elevatedMin: 35,
  criticalMin: 0,
};

export const WEATHER_ALERT_THRESHOLDS = {
  heat: {
    moderateAlertC: 40.0,
    criticalHeatwaveC: 45.0,
  },
  rain: {
    moderateRainMmHr: 7.5,
    criticalDownpourMmHr: 15.0,
  },
  windGusts: {
    moderateSquallKmh: 50.0,
    criticalStormKmh: 70.0,
  },
};

export const WMO_WEATHER_CODES: Record<number, { en: string; hi: string; isPrecip: boolean; icon: string }> = {
  0: { en: 'Clear sky', hi: 'साफ आसमान', isPrecip: false, icon: '☀️' },
  1: { en: 'Mainly clear', hi: 'मुख्यतः साफ', isPrecip: false, icon: '🌤️' },
  2: { en: 'Partly cloudy', hi: 'आंशिक बादल', isPrecip: false, icon: '⛅' },
  3: { en: 'Overcast', hi: 'घने बादल', isPrecip: false, icon: '☁️' },
  45: { en: 'Fog / Mist', hi: 'कोहरा / धुंध', isPrecip: false, icon: '🌫️' },
  48: { en: 'Depositing rime fog', hi: 'सघन कोहरा', isPrecip: false, icon: '🌫️' },
  51: { en: 'Light drizzle', hi: 'हल्की बूंदाबांदी', isPrecip: true, icon: '🌦️' },
  53: { en: 'Moderate drizzle', hi: 'मध्यम बूंदाबांदी', isPrecip: true, icon: '🌧️' },
  55: { en: 'Dense drizzle', hi: 'तेज बूंदाबांदी', isPrecip: true, icon: '🌧️' },
  61: { en: 'Slight rain', hi: 'हल्की बारिश', isPrecip: true, icon: '🌦️' },
  63: { en: 'Moderate rain', hi: 'मध्यम बारिश', isPrecip: true, icon: '🌧️' },
  65: { en: 'Heavy rain', hi: 'भारी बारिश', isPrecip: true, icon: '⛈️' },
  80: { en: 'Slight rain showers', hi: 'हल्की फुहारें', isPrecip: true, icon: '🌦️' },
  81: { en: 'Moderate showers', hi: 'मध्यम बौछारें', isPrecip: true, icon: '🌧️' },
  82: { en: 'Violent rain showers', hi: 'मूसलाधार बौछारें', isPrecip: true, icon: '⛈️' },
  95: { en: 'Thunderstorm', hi: 'गरज-चमक के साथ आंधी', isPrecip: true, icon: '⚡' },
  96: { en: 'Thunderstorm with slight hail', hi: 'ओलावृष्टि व आंधी', isPrecip: true, icon: '⛈️' },
  99: { en: 'Severe thunderstorm with hail', hi: 'गंभीर आंधी व ओले', isPrecip: true, icon: '🌪️' },
};

export const CITY_DEPARTMENTS = [
  { id: 'jmc-heritage', nameEn: 'Jaipur Municipal Corporation (Heritage)', nameHi: 'जयपुर नगर निगम (हेरिटेज)' },
  { id: 'jmc-greater', nameEn: 'Jaipur Municipal Corporation (Greater)', nameHi: 'जयपुर नगर निगम (ग्रेटर)' },
  { id: 'jda', nameEn: 'Jaipur Development Authority (JDA)', nameHi: 'जयपुर विकास प्राधिकरण' },
  { id: 'phed', nameEn: 'Public Health Engineering Dept (PHED Water)', nameHi: 'जन स्वास्थ्य अभियांत्रिकी विभाग (जल)' },
  { id: 'traffic-police', nameEn: 'Jaipur Traffic Police', nameHi: 'जयपुर यातायात पुलिस' },
  { id: 'jmrc', nameEn: 'Jaipur Metro Rail Corporation (JMRC)', nameHi: 'जयपुर मेट्रो रेल कॉर्पोरेशन' },
  { id: 'jvvnl', nameEn: 'Jaipur Vidyut Vitran Nigam (JVVNL Power)', nameHi: 'जयपुर विद्युत वितरण निगम' },
];
