import { Coordinates } from '../types';

export interface EmergencyPlace {
  id: string;
  name: string;
  nameHi: string;
  category: 'hospital' | 'police' | 'fire_station' | 'pharmacy';
  address: string;
  coordinates: Coordinates;
  distanceKm: number;
  openStatus: string;
  openStatusHi: string;
  isOpenNow: boolean;
  phone?: string;
  directionsUrl: string;
  zoneId: string;
}

export const JAIPUR_ZONE_EMERGENCY_DATA: Record<string, EmergencyPlace[]> = {
  'walled-city': [
    {
      id: 'hosp-sms-main',
      name: 'Sawai Man Singh (SMS) Hospital & Trauma Centre',
      nameHi: 'सवाई मानसिंह (एसएमएस) अस्पताल व ट्रॉमा सेंटर',
      category: 'hospital',
      address: 'JLN Marg, Ashok Nagar / Lal Kothi, Jaipur',
      coordinates: { lat: 26.9038, lng: 75.8164 },
      distanceKm: 1.8,
      openStatus: 'Open 24 Hours (Level-1 Trauma)',
      openStatusHi: '24 घंटे खुला (लेवल-1 ट्रॉमा सेंटर)',
      isOpenNow: true,
      phone: '0141-2560291',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Sawai+Man+Singh+Hospital+Jaipur',
      zoneId: 'walled-city',
    },
    {
      id: 'police-kotwali-wc',
      name: 'Kotwali Police Station',
      nameHi: 'कोतवाली पुलिस थाना',
      category: 'police',
      address: 'Badi Chaupar, Johari Bazar, Jaipur',
      coordinates: { lat: 26.9255, lng: 75.8270 },
      distanceKm: 0.3,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2604242',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Kotwali+Police+Station+Jaipur',
      zoneId: 'walled-city',
    },
    {
      id: 'fire-ghat-gate',
      name: 'Ghat Gate Municipal Fire Station',
      nameHi: 'घाट गेट नगर निगम अग्निशमन केंद्र',
      category: 'fire_station',
      address: 'Near Ghat Gate, Circular Road, Jaipur',
      coordinates: { lat: 26.9110, lng: 75.8345 },
      distanceKm: 1.2,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Ghat+Gate+Fire+Station+Jaipur',
      zoneId: 'walled-city',
    },
    {
      id: 'pharm-sms-janaushadhi',
      name: 'Jan Aushadhi 24x7 Pharmacy (SMS Campus)',
      nameHi: 'जन औषधि 24x7 मेडिकल स्टोर (एसएमएस परिसर)',
      category: 'pharmacy',
      address: 'Near Emergency Gate, SMS Hospital, Jaipur',
      coordinates: { lat: 26.9042, lng: 75.8168 },
      distanceKm: 1.9,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2560292',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=SMS+Hospital+Jaipur+Pharmacy',
      zoneId: 'walled-city',
    },
  ],
  'mansarovar': [
    {
      id: 'hosp-dhanwantri',
      name: 'Dhanwantri Life Care Hospital',
      nameHi: 'धन्वंतरि लाइफ केयर अस्पताल',
      category: 'hospital',
      address: 'Sector 11, New Sanganer Road, Mansarovar',
      coordinates: { lat: 26.8625, lng: 75.7680 },
      distanceKm: 0.9,
      openStatus: 'Open 24 Hours (Emergency/ICU)',
      openStatusHi: '24 घंटे खुला (आपातकालीन/आईसीयू)',
      isOpenNow: true,
      phone: '0141-2780700',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Dhanwantri+Life+Care+Hospital+Mansarovar+Jaipur',
      zoneId: 'mansarovar',
    },
    {
      id: 'police-mansarovar',
      name: 'Mansarovar Police Station',
      nameHi: 'मानसरोवर पुलिस थाना',
      category: 'police',
      address: 'Shipra Path, Sector 7, Mansarovar',
      coordinates: { lat: 26.8610, lng: 75.7610 },
      distanceKm: 0.7,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2780100',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Mansarovar+Police+Station+Jaipur',
      zoneId: 'mansarovar',
    },
    {
      id: 'fire-mansarovar-riico',
      name: 'Mansarovar RIICO Fire Station',
      nameHi: 'मानसरोवर रीको दमकल केंद्र',
      category: 'fire_station',
      address: 'RIICO Industrial Area, Mansarovar',
      coordinates: { lat: 26.8520, lng: 75.7530 },
      distanceKm: 1.6,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Mansarovar+Fire+Station+Jaipur',
      zoneId: 'mansarovar',
    },
    {
      id: 'pharm-apollo-vt',
      name: 'Apollo Pharmacy 24x7',
      nameHi: 'अपोलो फार्मेसी 24x7',
      category: 'pharmacy',
      address: 'VT Road Circle, Sector 3, Mansarovar',
      coordinates: { lat: 26.8670, lng: 75.7645 },
      distanceKm: 0.4,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2785500',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Apollo+Pharmacy+VT+Road+Mansarovar+Jaipur',
      zoneId: 'mansarovar',
    },
  ],
  'malviya-nagar': [
    {
      id: 'hosp-apex',
      name: 'Apex Super Speciality Hospital',
      nameHi: 'एपेक्स सुपर स्पेशलिटी अस्पताल',
      category: 'hospital',
      address: 'SP-6, Calgiri Marg, Malviya Nagar',
      coordinates: { lat: 26.8510, lng: 75.8190 },
      distanceKm: 0.8,
      openStatus: 'Open 24 Hours (Cardiac & Emergency)',
      openStatusHi: '24 घंटे खुला (हृदय व आपातकालीन विभाग)',
      isOpenNow: true,
      phone: '0141-2751871',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Apex+Hospital+Malviya+Nagar+Jaipur',
      zoneId: 'malviya-nagar',
    },
    {
      id: 'police-malviya-nagar',
      name: 'Malviya Nagar Police Station',
      nameHi: 'मालवीय नगर पुलिस थाना',
      category: 'police',
      address: 'Pradhan Marg, Sector 2, Malviya Nagar',
      coordinates: { lat: 26.8545, lng: 75.8155 },
      distanceKm: 0.6,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2550100',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Malviya+Nagar+Police+Station+Jaipur',
      zoneId: 'malviya-nagar',
    },
    {
      id: 'fire-malviya-ria',
      name: 'Malviya Industrial Area Fire Station',
      nameHi: 'मालवीय इंडस्ट्रियल एरिया दमकल केंद्र',
      category: 'fire_station',
      address: 'Road No. 1, Malviya Industrial Area',
      coordinates: { lat: 26.8450, lng: 75.8110 },
      distanceKm: 1.5,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Malviya+Nagar+Industrial+Area+Fire+Station+Jaipur',
      zoneId: 'malviya-nagar',
    },
    {
      id: 'pharm-medplus-gt',
      name: 'MedPlus 24x7 Pharmacy',
      nameHi: 'मेडप्लस 24x7 फार्मेसी',
      category: 'pharmacy',
      address: 'Opposite Gaurav Tower, Sector 9, Malviya Nagar',
      coordinates: { lat: 26.8550, lng: 75.8160 },
      distanceKm: 0.5,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2551234',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=MedPlus+Gaurav+Tower+Malviya+Nagar+Jaipur',
      zoneId: 'malviya-nagar',
    },
  ],
  'vaishali-nagar': [
    {
      id: 'hosp-global-heart',
      name: 'Global Heart & Super Speciality Hospital',
      nameHi: 'ग्लोबल हार्ट व सुपर स्पेशलिटी अस्पताल',
      category: 'hospital',
      address: 'Sector 5, Chitrakoot, Vaishali Nagar',
      coordinates: { lat: 26.9020, lng: 75.7350 },
      distanceKm: 1.1,
      openStatus: 'Open 24 Hours (Emergency/Trauma)',
      openStatusHi: '24 घंटे खुला (इमरजेंसी/ट्रॉमा)',
      isOpenNow: true,
      phone: '0141-2440300',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Global+Heart+Hospital+Chitrakoot+Jaipur',
      zoneId: 'vaishali-nagar',
    },
    {
      id: 'police-vaishali-nagar',
      name: 'Vaishali Nagar Police Station',
      nameHi: 'वैशाली नगर पुलिस थाना',
      category: 'police',
      address: 'Amrapali Circle, Gandhi Path, Vaishali Nagar',
      coordinates: { lat: 26.9080, lng: 75.7430 },
      distanceKm: 0.5,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2350100',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Vaishali+Nagar+Police+Station+Jaipur',
      zoneId: 'vaishali-nagar',
    },
    {
      id: 'fire-200ft-bypass',
      name: '200 Feet Bypass Fire Substation',
      nameHi: '200 फीट बाईपास दमकल सब-स्टेशन',
      category: 'fire_station',
      address: 'Heerapura Junction, 200 Feet Bypass Road',
      coordinates: { lat: 26.8920, lng: 75.7310 },
      distanceKm: 2.1,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Heerapura+Fire+Station+Jaipur',
      zoneId: 'vaishali-nagar',
    },
    {
      id: 'pharm-wellness-forever',
      name: 'Wellness Forever 24x7 Chemist',
      nameHi: 'वेलनेस फॉरएवर 24x7 केमिस्ट',
      category: 'pharmacy',
      address: 'Near Amrapali Plaza, Amrapali Marg, Vaishali Nagar',
      coordinates: { lat: 26.9075, lng: 75.7420 },
      distanceKm: 0.3,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2355550',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Wellness+Forever+Amrapali+Marg+Vaishali+Nagar+Jaipur',
      zoneId: 'vaishali-nagar',
    },
  ],
  'raja-park': [
    {
      id: 'hosp-anand',
      name: 'Anand Hospital & Research Centre',
      nameHi: 'आनंद अस्पताल व रिसर्च सेंटर',
      category: 'hospital',
      address: 'Dhuleshwar Garden / Lane 4, Raja Park',
      coordinates: { lat: 26.8985, lng: 75.8290 },
      distanceKm: 0.5,
      openStatus: 'Open 24 Hours (Emergency)',
      openStatusHi: '24 घंटे खुला (आपातकालीन)',
      isOpenNow: true,
      phone: '0141-2621122',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Anand+Hospital+Raja+Park+Jaipur',
      zoneId: 'raja-park',
    },
    {
      id: 'police-jawahar-nagar',
      name: 'Jawahar Nagar Police Station',
      nameHi: 'जवाहर नगर पुलिस थाना',
      category: 'police',
      address: 'Sector 4, Jawahar Nagar, Near Raja Park',
      coordinates: { lat: 26.8930, lng: 75.8320 },
      distanceKm: 0.8,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2650100',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Jawahar+Nagar+Police+Station+Jaipur',
      zoneId: 'raja-park',
    },
    {
      id: 'fire-moti-doongri',
      name: 'Moti Doongri Fire Substation',
      nameHi: 'मोती डूंगरी दमकल सब-स्टेशन',
      category: 'fire_station',
      address: 'JLN Marg, Near Birla Mandir',
      coordinates: { lat: 26.8920, lng: 75.8150 },
      distanceKm: 1.6,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Moti+Doongri+Fire+Station+Jaipur',
      zoneId: 'raja-park',
    },
    {
      id: 'pharm-dadha-raja-park',
      name: 'Dadha Chemist 24x7',
      nameHi: 'दाढ़ा केमिस्ट 24x7',
      category: 'pharmacy',
      address: 'Lane 1, Main Market, Raja Park',
      coordinates: { lat: 26.8965, lng: 75.8275 },
      distanceKm: 0.2,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2620500',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Dadha+Chemist+Raja+Park+Jaipur',
      zoneId: 'raja-park',
    },
  ],
  'sanganer': [
    {
      id: 'hosp-mg-sanganer',
      name: 'Mahatma Gandhi Hospital & Medical College',
      nameHi: 'महात्मा गांधी अस्पताल व मेडिकल कॉलेज',
      category: 'hospital',
      address: 'RIICO Institutional Area, Sitapura / Sanganer',
      coordinates: { lat: 26.7820, lng: 75.8310 },
      distanceKm: 2.8,
      openStatus: 'Open 24 Hours (Tertiary Trauma)',
      openStatusHi: '24 घंटे खुला (सुपर स्पेशलिटी ट्रॉमा सेंटर)',
      isOpenNow: true,
      phone: '0141-2771777',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Mahatma+Gandhi+Hospital+Sitapura+Jaipur',
      zoneId: 'sanganer',
    },
    {
      id: 'police-sanganer-thana',
      name: 'Sanganer Police Thana',
      nameHi: 'सांगानेर पुलिस थाना',
      category: 'police',
      address: 'Main Bazaar Road, Sanganer Town',
      coordinates: { lat: 26.8180, lng: 75.7710 },
      distanceKm: 0.6,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2730100',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Sanganer+Police+Station+Jaipur',
      zoneId: 'sanganer',
    },
    {
      id: 'fire-sitapura-fire',
      name: 'Sitapura RIICO Fire Station',
      nameHi: 'सीतापुरा रीको अग्निशमन केंद्र',
      category: 'fire_station',
      address: 'Phase 3, Sitapura Industrial Area, Sanganer',
      coordinates: { lat: 26.7910, lng: 75.8190 },
      distanceKm: 2.5,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Sitapura+Fire+Station+Jaipur',
      zoneId: 'sanganer',
    },
    {
      id: 'pharm-sanjeevani-sanganer',
      name: 'Sanjeevani 24x7 Medical Store',
      nameHi: 'संजीवनी 24x7 मेडिकल स्टोर',
      category: 'pharmacy',
      address: 'Near Sanganer Bus Stand, Tonk Road',
      coordinates: { lat: 26.8205, lng: 75.7730 },
      distanceKm: 0.4,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2731155',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Sanjeevani+Medical+Store+Sanganer+Jaipur',
      zoneId: 'sanganer',
    },
  ],
  'amer': [
    {
      id: 'hosp-amer-satellite',
      name: 'Amer Government Satellite Hospital',
      nameHi: 'आमेर राजकीय सैटेलाइट अस्पताल',
      category: 'hospital',
      address: 'Delhi-Jaipur Highway, Near Kunda, Amer',
      coordinates: { lat: 26.9890, lng: 75.8520 },
      distanceKm: 0.7,
      openStatus: 'Open 24 Hours (Emergency Services)',
      openStatusHi: '24 घंटे खुला (आपातकालीन सेवाएं)',
      isOpenNow: true,
      phone: '0141-2530230',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Government+Hospital+Amer+Jaipur',
      zoneId: 'amer',
    },
    {
      id: 'police-amer-thana',
      name: 'Amer Police Station',
      nameHi: 'आमेर पुलिस थाना',
      category: 'police',
      address: 'Near Amer Fort Elephant Stand, Amer',
      coordinates: { lat: 26.9840, lng: 75.8505 },
      distanceKm: 0.4,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2530100',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Amer+Police+Station+Jaipur',
      zoneId: 'amer',
    },
    {
      id: 'fire-jal-mahal-fire',
      name: 'Jal Mahal Emergency Fire Post',
      nameHi: 'जल महल आपातकालीन दमकल चौकी',
      category: 'fire_station',
      address: 'Amer Road, Opposite Jal Mahal Promenade',
      coordinates: { lat: 26.9550, lng: 75.8450 },
      distanceKm: 2.9,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Jal+Mahal+Fire+Station+Jaipur',
      zoneId: 'amer',
    },
    {
      id: 'pharm-amer-medical',
      name: 'Amer Chemist & Day-Night Pharmacy',
      nameHi: 'आमेर केमिस्ट व डे-नाइट मेडिकल',
      category: 'pharmacy',
      address: 'Main Gate Bazar, Amer Town',
      coordinates: { lat: 26.9860, lng: 75.8510 },
      distanceKm: 0.3,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2530400',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Amer+Chemist+Main+Bazar+Amer+Jaipur',
      zoneId: 'amer',
    },
  ],
  'jagatpura': [
    {
      id: 'hosp-ehcc',
      name: 'Eternal Hospital (EHCC Super Speciality)',
      nameHi: 'इटरनल हॉस्पिटल (ईएचसीसी सुपर स्पेशलिटी)',
      category: 'hospital',
      address: '3 A, Jagatpura Road, Near Jawahar Circle',
      coordinates: { lat: 26.8395, lng: 75.8075 },
      distanceKm: 1.4,
      openStatus: 'Open 24 Hours (NABH Accredited Trauma/Heart)',
      openStatusHi: '24 घंटे खुला (हृदय व आपातकालीन ट्रॉमा सेंटर)',
      isOpenNow: true,
      phone: '0141-5174000',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Eternal+Hospital+EHCC+Jaipur',
      zoneId: 'jagatpura',
    },
    {
      id: 'police-ramnagariya',
      name: 'Ramnagariya Police Station',
      nameHi: 'रामनगरिया पुलिस थाना',
      category: 'police',
      address: 'Mahal Road, Near Akshay Patra, Jagatpura',
      coordinates: { lat: 26.8190, lng: 75.8450 },
      distanceKm: 1.0,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2770100',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Ramnagariya+Police+Station+Jagatpura+Jaipur',
      zoneId: 'jagatpura',
    },
    {
      id: 'fire-jagatpura-fire',
      name: 'Malviya Nagar / Jagatpura Link Fire Station',
      nameHi: 'मालवीय नगर / जगतपुरा लिंक दमकल केंद्र',
      category: 'fire_station',
      address: 'Calgiri Marg / Jagatpura Connector',
      coordinates: { lat: 26.8380, lng: 75.8200 },
      distanceKm: 1.8,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Malviya+Nagar+Fire+Station+Jaipur',
      zoneId: 'jagatpura',
    },
    {
      id: 'pharm-lifeline-jagatpura',
      name: 'Lifeline 24x7 Pharmacy',
      nameHi: 'लाइफलाइन 24x7 फार्मेसी',
      category: 'pharmacy',
      address: 'Mahal Road, Opp. Unique Towers, Jagatpura',
      coordinates: { lat: 26.8240, lng: 75.8390 },
      distanceKm: 0.5,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2775600',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Lifeline+Pharmacy+Mahal+Road+Jagatpura+Jaipur',
      zoneId: 'jagatpura',
    },
  ],
  'cscheme-civillines': [
    {
      id: 'hosp-sdmh',
      name: 'Santokba Durlabhji Memorial Hospital (SDMH)',
      nameHi: 'संतोकबा दुर्लभजी मेमोरियल अस्पताल (एसडीएमएच)',
      category: 'hospital',
      address: 'Bhawani Singh Marg, Near Rambagh Circle, C-Scheme',
      coordinates: { lat: 26.8995, lng: 75.8030 },
      distanceKm: 1.1,
      openStatus: 'Open 24 Hours (Emergency Trauma)',
      openStatusHi: '24 घंटे खुला (आपातकालीन ट्रॉमा)',
      isOpenNow: true,
      phone: '0141-2566251',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Santokba+Durlabhji+Hospital+Jaipur',
      zoneId: 'cscheme-civillines',
    },
    {
      id: 'police-ashok-nagar',
      name: 'Ashok Nagar Police Station',
      nameHi: 'अशोक नगर पुलिस थाना',
      category: 'police',
      address: 'Bhagwan Das Road, C-Scheme',
      coordinates: { lat: 26.9090, lng: 75.8060 },
      distanceKm: 0.7,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2370100',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Ashok+Nagar+Police+Station+Jaipur',
      zoneId: 'cscheme-civillines',
    },
    {
      id: 'fire-bani-park',
      name: 'Bani Park Central Fire Station',
      nameHi: 'बनी पार्क मुख्य अग्निशमन केंद्र',
      category: 'fire_station',
      address: 'Collectorate Circle, Bani Park',
      coordinates: { lat: 26.9280, lng: 75.7940 },
      distanceKm: 1.9,
      openStatus: 'Open 24 Hours (Emergency 101)',
      openStatusHi: '24 घंटे आपातकालीन सेवा (101)',
      isOpenNow: true,
      phone: '101',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Bani+Park+Fire+Station+Jaipur',
      zoneId: 'cscheme-civillines',
    },
    {
      id: 'pharm-c-scheme-med',
      name: 'Sindhi Camp 24x7 Medical & Surgical',
      nameHi: 'सिंधी कैंप 24x7 मेडिकल स्टोर',
      category: 'pharmacy',
      address: 'Station Road, Near Sindhi Camp Bus Terminal',
      coordinates: { lat: 26.9205, lng: 75.7995 },
      distanceKm: 1.2,
      openStatus: 'Open 24 Hours',
      openStatusHi: '24 घंटे खुला',
      isOpenNow: true,
      phone: '0141-2375500',
      directionsUrl: 'https://www.google.com/maps/dir/?api=1&destination=Sindhi+Camp+Medical+Store+Jaipur',
      zoneId: 'cscheme-civillines',
    },
  ],
};

/**
 * Returns the nearest emergency hospital for a given zone ID.
 */
export function getNearestHospitalForZone(zoneId: string): EmergencyPlace {
  const list = JAIPUR_ZONE_EMERGENCY_DATA[zoneId] || JAIPUR_ZONE_EMERGENCY_DATA['walled-city'];
  const hospital = list.find((p) => p.category === 'hospital');
  return hospital || list[0];
}

/**
 * Returns all static emergency services configured for a zone.
 */
export function getZoneEmergencyPlaces(zoneId: string): EmergencyPlace[] {
  return JAIPUR_ZONE_EMERGENCY_DATA[zoneId] || JAIPUR_ZONE_EMERGENCY_DATA['walled-city'] || [];
}
